# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f46a9e46b6b36029f1e781c08cca3d2d4aa614ac7fc08f44a30c8699750864caa10fbf35ec0113249a5c8008fd8836fd4305041f5088d19291f1a8e93de31297

test:
  secret_key_base: 9a24f4a2c8000b8c04fafd6a02be90252b15f35a6baab925341ca654cb9291b762003c8fe5566314e5fc618745bc2d2e2c77a71e76b88b2c342cece51036db51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
